# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "geekinc-ca/geekbox"
    config.vm.hostname = "mysql"
    config.vm.network "private_network", ip: "192.168.44.10"
    config.vm.synced_folder ".", "/var/www/public", :mount_options => ["dmode=777", "fmode=777"]
    # Bugfix for "Cable connected: off"
    config.vm.provider :virtualbox do |vm|
       vm.customize [
             "modifyvm", :id,
                   "--cableconnected1", "on",
                       ]
	end
end
